### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by xCuri0** [elenapan/dotfiles#10]
Do you have a list of dependencies this theme requires ?

**Comment by xCuri0** [comment]
@elenapan what about fonts ? There seem to be missing fonts

**Comment by elenapan** [comment]
I am not using any special fonts on this theme. I specifically use the generic "sans" and "monospace" as fonts in the configs I publish so whatever you have on your system will work.

Maybe you forgot to install fonts? You said you are on a clean Arch installation, which does not include any fonts by default.

**Comment by xCuri0** [comment]
It seems like the manta theme requires a font I don't have. The lovelace once works fine though. But I can't seem to get the GTK theme working on either (lxappearance does nothing)

**Comment by elenapan** [comment]
The manta theme requires a [Nerd Font](https://nerdfonts.com/#downloads). This is noted in the README.

Where have you placed the GTK theme folder? It should be either in `/usr/share/themes` or `~/.themes/`.

**Comment by xCuri0** [comment]
@elenapan which nerd font did you download

Also I put it into ~/.local/share/themes. It shows up in lxappearance but selecting it does nothing

**Comment by elenapan** [comment]
Any font is alright, as all of them have the same icons. I suggest Iosevka, it is very good looking.

Yeah `~/.local/share/themes` works as well. However I am not sure why lxappearance shows nothing. Do other themes work? Have you tried installing `arc-gtk-theme` for example?

**Comment by xCuri0** [comment]
@elenapan it shows but when I set it it does nothing

**Comment by elenapan** [comment]
What application are you trying it on? Some of them do not use the new theme right away, even if you restart them. I suggest logging in and out or even rebooting to make sure.

Anyway, if not even the Arc theme works in your system, you might need to look into it. I cannot help you with that.

**Comment by elenapan** [comment]
The manta theme is old. I have added and removed a ton of stuff to my config since then so I cannot guarantee it will work.

Also you are using the bar config for the lovelace theme. It is trying to load icons for the taglist, which do not even exist in the manta directory.

The best I can do is point you to [the commit right before I posted the lovelace theme](https://github.com/elenapan/dotfiles/tree/edf5211b6e34d6d1fe5350806f21eeb7fc6d9989). The manta theme should work but you will be missing some features like the sidebar that I added recently.

Alternatively, you can only grab `bars.lua` from that snapshot, copy it into your current `bars.lua` and see if it works.

**Comment by elenapan** [comment]
Bump! Is your issue resolved?

**Comment by xCuri0** [comment]
@elenapan just tried cloning the whole old repository and the bar appears correctly. But the font still doesn't work

**Comment by elenapan** [comment]
Hmm, have you run `fc-cache` after copying the fonts to `/usr/share/fonts`? 
Also can you confirm the font is selectable in `lxappearance`?

**Comment by elenapan** [comment]
For me there is font selection at the bottom as you can see:

![image](https://user-images.githubusercontent.com/31134749/51795666-01592d80-21f0-11e9-98ac-1f5a1e66e940.png)

If you click it a font browser will appear.

But I think I figured out what is wrong.

In `theme.lua` change `theme.font = "monospace 12"` to `theme.font = "iosevka nerd font 12"` (or however it is named, you can check that in Lxappearance as well).

The problem was that I had set my `fontconfig` to use Iosevka as the default monospace font, but since you do not have that, it was just using your system's monospace font.

**Comment by xCuri0** [comment]
@elenapan heres a screenshot
![2019-01-27-144558_1600x900_scrot](https://user-images.githubusercontent.com/29529557/51799057-6b022780-2242-11e9-9204-9485a3ad1335.png)

**Comment by xCuri0** [comment]
@elenapan thanks that works. now how do I get my termite themed. i didn't find any files for it in the repo

**Comment by elenapan** [comment]
Well the colors in .Xresources format are [here](https://github.com/elenapan/dotfiles/blob/master/.xfiles/manta). It is easy to port them to termite's format. The config options are pretty clear in my opinion.

**Comment by xCuri0** [comment]
@elenapan Thanks it works now. The only problem I have are the missing window buttons on firefox

**Comment by elenapan** [comment]
You can toggle titlebars on any client with `super + t`.

But there is a rule to spawn Firefox without titlebars in my config.
In `rc.lua` look for `Titlebars OFF`. Under this comment there is a list of classes that have their titlebar disabled by default. You can remove "Firefox" from there.

If you mean buttons next to the tabs in Firefox see my comment [here](https://github.com/elenapan/dotfiles/issues/9#issuecomment-455292665).
