### ISSUE TITLE
Missing transparency on the bottom icons bar when hovered over a window

### ISSUE THREAD

**Issue by DanielBiegler** [elenapan/dotfiles#109]
Does this only happen to me? See the following image: 

![image](https://user-images.githubusercontent.com/14810858/91713406-00397080-eb8a-11ea-980c-e306701ce166.png)

Since this theme (amarena) is so flat and clean, I think adding a border would take away of it's simplicity. How about adding shadow behind the icons? I'm still learning the inner workings of Awesome so I'm not sure of all the capabilities.

Also happens with the sidebar, see top right corner here: 

![image](https://user-images.githubusercontent.com/14810858/91732735-ed826400-eba8-11ea-8b6c-9159e68afc22.png)

**Comment by elenapan** [comment]
Hi there,

This is because you need to run a compositor (I suggest [this fork of picom](https://github.com/ibhagwan/picom)) in order for your desktop to support transparency.
This should fix both the dock and the sidebar issues.

I provide my picom configuration [here](https://github.com/elenapan/dotfiles/blob/master/config/picom/picom.conf).

Check out how you can run `picom` [automatically on startup](https://github.com/elenapan/dotfiles/wiki/Autostart).

**Comment by DanielBiegler** [comment]
Thank you very much. Works now!
