### ISSUE TITLE
what is the sidebar?

### ISSUE THREAD

**Issue by rudrab** [elenapan/dotfiles#111]
Hi,
This is not an issue, but a help request. 
In sidebar like https://preview.redd.it/glzrkk83f4621.png?width=640&crop=smart&auto=webp&s=bbce2fb2f490d9f505f3ca26a98ae7506d0ff01d , how the sidebar is made? Is it some feature of AwesomeWM? 
I am in gnome and use conky, but after looking at your sidebar, my sidebar with conky looks so dated.

**Comment by elenapan** [comment]
Hi there

The AwesomeWM widget system has insane capabilities.
You can think of it as `polybar`+`Conky` on steroids, and it still would not be close.

Unlike other bars, it can display images, has support for various built-in shaped widgets like progress-bars, and its contents can be arranged in any way you can imagine. Plus, you can add custom logic since the configuration is just Lua code.

The sidebar is no different than any other bar. It is a box which is vertically maximized and placed at the edge of the screen.
You can then insert various widgets into it (clocks, progress bars, custom text, icons).

You can find the code for this sidebar [here](https://github.com/elenapan/dotfiles/blob/master/config/awesome/elemental/sidebar/lovelace.lua).

Also I suggest taking a look at the [AwesomeWM widget tutorial ](https://awesomewm.org/apidoc/documentation/03-declarative-layout.md.html) if you are interested in creating your own widgets.

**Comment by elenapan** [comment]
Closing as the question was answered.
