### ISSUE TITLE
Having errors while opening awesomewm

### ISSUE THREAD

**Issue by F4zii** [elenapan/dotfiles#117]
im getting an error while opening my desktop:
Will you be able to help me out here? kind of a newbie with awesomewm

![image](https://user-images.githubusercontent.com/44242259/93030016-690ff680-f628-11ea-9b59-1850a3ea07c6.png)

```
Stack traceback:
    /home/iddos/.config/awesome/rc.lua:189: in main chunk
error: /home/iddos/.config/awesome/rc.lua:189: attempt to call a nil value (field 'connect_signal')

**Comment by elenapan** [comment]
Hi there,

It is stated in the [Setup](https://github.com/elenapan/dotfiles#setup) section of the README that the [git version of AwesomeWM](https://github.com/awesomeWM/awesome/) should be installed. The error will go away if you do that.

**Comment by F4zii** [comment]
Oh thank you very much, ill try that

**Comment by F4zii** [comment]
Hey, thanks for the response, I tried that out and got another issue, wanted to ask if you encountered it before - https://github.com/awesomeWM/awesome/issues/3177

**Comment by elenapan** [comment]
It has not happened to me since I have not updated my AwesomeWM in a long time.
But I did notice that quite a few people have the same issue lately:

- https://github.com/awesomeWM/awesome/issues/3168
- https://reddit.com/r/awesomewm/comments/iq8dfx/error_installing_awesomegit/
- https://reddit.com/r/awesomewm/comments/iskkoa/failed_to_build_awesomegit_on_archlinux/

Until it gets fixed you could try installing it from an older commit.

**Comment by Elv13** [comment]
> Until it gets fixed you could try installing it from an older commit.

I fixed it in git-master. It's not something an older commit can really fix (unless it is so old it predates the feature itself). The problem was introduced by a new release of one of our dependencies. It created a naming collision. Since there is no namespaces in C, this happens.

**Comment by elenapan** [comment]
Closing since both issues were solved.
