### ISSUE TITLE
Questions about picom configuration

### ISSUE THREAD

**Issue by JavaCafe01** [elenapan/dotfiles#118]
First of all, I would like to say that you have such an amazing setup! Your configs are also neatly done, and are a great guide/help for us awesome users. 

I have a couple of questions about your picom setup. I use the same picom fork as you do, and was using the `xrender` backend to have nice corners like these:

![image](https://user-images.githubusercontent.com/33443763/93708813-2a79b080-faee-11ea-856a-d1653a076464.png)

However, I have fallen for the appeal of blur and have switched to the `glx` backend (as I recall blur only works on `glx`). The corners end up like these: 

![image](https://user-images.githubusercontent.com/33443763/93708863-82181c00-faee-11ea-912e-609f2fe3f7f5.png)

It has these weird borders around just part of the corner. On your setup, I see a light border but around the whole window instead of like mine, which is better in my opinion. I'm just wondering if you found a work around for that? Thanks!

**Comment by elenapan** [comment]
Hi there,

That border around the whole window was bothering me as well (mostly because I do not know why it appeared when there was no `picom` configuration option for it). Since I updated `picom` and started using `--experimental-backends`, the border is gone.

This is how I launch `picom`:
```shell
picom --experimental-backends --config ~/.config/picom/picom.conf
```

Also, you can find [my `picom` config](https://github.com/elenapan/dotfiles/blob/master/config/picom/picom.conf) here. Maybe it will make a difference.

By the way, blur also works on `xrender`, but you can only get that super strong `kawase` blur on `glx`.

**Comment by JavaCafe01** [comment]
@elenapan Thanks for the reply! If I use rounded corners with `--experimental-backends` and with shadows, I get this: 
![image](https://user-images.githubusercontent.com/33443763/93845237-f7056600-fc54-11ea-9282-dbb533319f0e.png)

I realized that this backend is still in the works with rounded corners for picom, so I will close this as it's not really related to your dotfiles anymore. Thanks for your help!
