### ISSUE TITLE
How to get multi-monitor setup working with Amarena theme?

### ISSUE THREAD

**Issue by ejuarezg** [elenapan/dotfiles#124]
Hi,

I'm enjoying the Amarena theme and would like to get a dual-monitor setup going. I used the recipe over at https://awesomewm.org/recipes/xrandr/ to get started but switching to different arrangements does nothing. After 4 seconds, the chosen configuration should be applied but, in my case, the notification does not disappear after 4 seconds and the config does not get applied.

Do you have any resources to get a multi-monitor setup working? Anything would be greatly appreciated.

**Comment by elenapan** [comment]
Hi there,

Let me start by saying I have almost 0 experience with multiple monitors.

My suggestion would be to install and use `arandr` in order to graphically configure and rearrange your monitors. After applying your configuration, you might need to restart Awesome with <kbd>super + shift + r</kbd>.
When you are happy with it, `arandr` can generate a script that you can run on startup (see [Autostart](https://github.com/elenapan/dotfiles/wiki/Autostart)) in order to apply your monitor configuration automatically on login.

If `arandr` does not solve your problems we can take a look at that `xrandr.lua` script together.

Let me know if you need more help.

**Comment by ejuarezg** [comment]
Hey, thanks for the arandr suggestion. It seems to work fine for my purposes. If I ever get `xrandr.lua` working, I'll post a comment here. The features it offers would be a nice to have.

**Comment by ejuarezg** [comment]
By the way, when I move windows to the another monitor, they move back to the main monitor when I change tags. Do you have any idea why this may be happening?

**Comment by elenapan** [comment]
Hi there, sorry for the delay.

I am not exactly sure why this is happening.

The only signal I have related to tag switching is this:
https://github.com/elenapan/dotfiles/blob/b7786196dafdcb44342531cbc952a8f13a404980/config/awesome/rc.lua#L1075-L1084

Perhaps commenting it out temporarily could solve the issue.

With a quick look in rc.lua, apart from that signal, only `awful.rules` could cause this.

I will try to further look into this during the weekend.

**Comment by ejuarezg** [comment]
I commented out the code block you showed but that didn't work, unfortunately. Here are some further things I've discovered:
- The monitor in which the window is opened does not matter. Clicking on a tag on the other monitor will move it to that tag.
- If I scroll over the tags, instead of clicking, to change into another tag, the window is not moved.

**Comment by EllatharTheHalfling** [comment]
I can only currently offer some insight into the most recent comment, as that is the only one i've experienced and looked into extensively to fit my uses before realizing i didn't really need to change much at all.

find this in keys.lua and comment it out 
```
    awful.button({ modkey }, 1, function(t)
        if client.focus then
            client.focus:move_to_tag(t)
        end
    end),
```
alternatively, if you'd like to keep the functionality change `modkey` to one of the keys defined at the start of the `keys.lua` (if using these are unmodified from the dotfiles these should be `altkey`, `superkey`, `ctrlkey`, and `shiftkey`), file. upon reload you should be good.

an explanation of what's going on:
`modkey` is a remnant of original AwesomeWM configs and is no longer defined. so what was once supposed to be a modifier key + mouse button event to allow you to move a window to another screen without changing to that screen. without modkey being set as a variable it makes the function a redundant method of the function below it. rather than erroring out as an invalid function. anything set that isn't a variable is just skipped over as if it's blank space. I'm not sure if that's a lua thing or an AwesomeWM thing, but it just so happens to be that way.

the way this sections is intended to work is:
Left-click a tag: switch to that tag and view it, or switch back to the tag that was selected immediately prior to it.

Modkey+LClick: move window to tag without switching to that tag

RClick: move window to tag and switch to that tag.

Modkey+RClick: select a tag to move selected windows to (from the current tag and/or others). this one confused me at first, in terms of function and i'm still not sure how to fully explain it. but what it allows is for you to highlight a tag with a window selected. and you can do this with multiple windows on that tag, move to another tag (by scrolling) and then select more windows there if you want. then if you release modkey and then RClick the highlighted tag one more time it moves all windows previously set to the highlighted tag over at once.

if the modkey functions are not desired then you can comment out or remove them from the file without any consequence currently.

Hope this helps
this should fix all three issues you noticed in the last comment
they were not brought to elenapan's attention prior because I had intention of bringing all non-OS specific issues to light (and how to deal with/fix/change functions of) once I had compiled a solid list of them. but since this issue had come up from another user it seemed better to bring it up now.

**Comment by ejuarezg** [comment]
Thank you, Ellathar, for the in-depth explanation. This solved my issue. I suspected the problem was in `keys.lua` but I never would have guessed it was that.

**Comment by elenapan** [comment]
Thank you @EllatharTheHalfling for figuring this out!
