### ISSUE TITLE
day_of_the_week.lua issues

### ISSUE THREAD

**Issue by OliverNChalk** [elenapan/dotfiles#132]
Here is the transcribed error notification:
```
~/.config/awesome/noodle/day_of_the_week.lua:78: attempt to index a nil value (field '?')
```

I had a look at the line and am struggling to see any obvious error. I have never written lua before so am struggling to interpret the error message. Wondering if this issue has been seen before and is an easy fix, or for some more guidance on how to debug this.

Thanks!

**Comment by ceuk** [comment]
What's the output when you run `date +%u`?

**Comment by OliverNChalk** [comment]
Running `date +%u` I get `4`

**Comment by ceuk** [comment]
If you're getting 4 then I don't think it'll be that -- do you have a file at `~/.Xresources`?

**Comment by OliverNChalk** [comment]
I've just copied a colorscheme from the internet to ensure it was available for use by `.config/awesome`:
```
! Project:    Nord XResources
! Version:    0.1.0
! Repository: https://github.com/arcticicestudio/nord-xresources
! License:    MIT

#define nord0 #2E3440
#define nord1 #3B4252
#define nord2 #434C5E
#define nord3 #4C566A
#define nord4 #D8DEE9
#define nord5 #E5E9F0
#define nord6 #ECEFF4
#define nord7 #8FBCBB
#define nord8 #88C0D0
#define nord9 #81A1C1
#define nord10 #5E81AC
#define nord11 #BF616A
#define nord12 #D08770
#define nord13 #EBCB8B
#define nord14 #A3BE8C
#define nord15 #B48EAD

*.foreground:   nord4
*.background:   nord0
*.cursorColor:  nord4
*fading: 35
*fadeColor: nord3

*.color0: nord1
*.color1: nord11
*.color2: nord14
*.color3: nord13
*.color4: nord9
*.color5: nord15
*.color6: nord8
*.color7: nord5
*.color8: nord3
*.color9: nord11
*.color10: nord14
*.color11: nord13
*.color12: nord9
*.color13: nord15
*.color14: nord7
*.color15: nord6
```

**Comment by ceuk** [comment]
What happens if you change line 78 to something like this instead?

`dotw_containers[index].bg = '#00000000'`

**Comment by OliverNChalk** [comment]
I have made this change and it is currently working but the issue does seem to come and go, so I will wait a little before updating / marking this issue closed.

**Comment by ceuk** [comment]
if that change fixed it then there might be an issue with your xcolor variables (see [here](https://github.com/elenapan/dotfiles/blob/master/config/awesome/noodle/day_of_the_week.lua#L12-L21)).

Hardcoding the colour to black isn't a great solution and you will likely be getting issues in other places because of the same underlying problem. 

In the meantime you could also try changing that  line 78 to something like:

```lua
dotw_containers[index].bg = index < 6 and x.color9 or x.color13
```

That will at least give the right colours. However, if you get a different error then I'd make sure that [these lines](https://github.com/elenapan/dotfiles/blob/master/config/awesome/rc.lua#L149-L174) are present in your rc.lua and maybe check that xrdb is available?˘(`which xrdb`). 


If that gives you a different error you know it's a problem with your xcolors otherwise

**Comment by OliverNChalk** [comment]
I seem to be having more general them-wide wide issues with time, weather etc. Closing this issue and will open another if I find a more concrete cause
