### ISSUE TITLE
Missing Xresources and HiDPI possibilities

### ISSUE THREAD

**Issue by lukasbash** [elenapan/dotfiles#14]
Hello,

first of all I honor your work and I think you really create great themes and setups for the Unix community. Thank you for your efforts!

Your latest version (Skyfall) inspired me to try out the theme. As I am using arch linux and awesomewm for a while it seems to be quite straight forward to set it up.
I would have some general questions to you.

1.) What font do you use for UI and the terminal?

2.) Where are your xst settings? Am I wrong or don't you have to configure them in the .Xresources with the `st.` namespace?

3.) Did you ever try, or do you have any feedback using your theme(s) on a HiDPI screen? I am precisely using a 4K screen - when I am on the way on a 15 inch notebook screen and at a 32 inch screen at work. Anything I should take care about? Other than the Xft dpi setting in the resources..

Thank you very much again for your time and your efforts!

**Comment by elenapan** [comment]
1. Roboto Condensed for UI and Anka/Coder Condensed for the terminal. Additionally I use some icons from Typicons and Nerd Fonts.

2. I upload my colorschemes in the `.xfiles` folder in my repo so people can just take the colorscheme file and use it without having to delete any of my `~/.Xresources` options. As a result I rarely update that file on my repo.
My xst settings are just:
```
st.borderpx: 45
st.termname: st
st.bold_font: 1
st.font: monospace:size=11
```
(I use `fontconfig` to set my monospace font globally)

3. You are in luck, because the screenshot I uploaded was from my new 4K screen. Ever since I started using it I took care of scaling issues I had with my themes. Now everything scales with DPI (except some variables in older themes which I do not use anymore, but it is super easy to fix). Just setting for example `Xft.dpi: 288` in your `~/.Xresources` should be enough for AwesomeWM to scale everything properly.

**Comment by elenapan** [comment]
Bump! Do you have any more questions/issues?

**Comment by lukasbash** [comment]
Oh damn, sorry. I forgot to get back to you.
So far I did not have any more issues.

Still I have the one or the other question. Maybe it is not really related to your theme at all, still maybe we could use this conversation to clarify those:

1.) I am using awesome as a "productive" mode, while developing or doing anything else with regard to coding. As an alternative I use a full desktop environment (gnome in this case). As a display manager I use gdm. From there I log in to either awesome or another session.
Sometimes it seems that gnome and the .Xresources are in conflict, especially with regard to scaling. Did you ever use awesome with a full DE side by side? And if, did you discover any issues?

2.) The environment variables for the GTK applications only seem to work with integers. As a scale factor of 200% is too much for me, I would like to set e.g. 125% or maybe 150%.
Do you know how I can set it properly.
Note: I am aware that I could set the scaling factor to 200% and then "zoom" out by e.g. 75% again, using `xrandr`. I would like to avoid this because it results in blurry images/font in some cases (even with full hinting).
Any feedback on this?

**Comment by elenapan** [comment]
1. I have never used Awesome alogside a DE, so I cannot help you there. Since you are using GNOME:

    Yesterday [the pull request for fractional scaling support](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/5) was finally merged into GNOME. So with the latest git version of GNOME you will be able to use `gsettings set org.gnome.desktop.interface scaling-factor 2` with fractional numbers. The text scaling setting already works with fractional numbers: `gsettings set org.gnome.desktop.interface text-scaling-factor 1.5`.
Maybe these settings will achieve a more uniform result than setting `Xft.dpi` and `GDK_SCALE` since all GNOME apps will respect `gsettings`.

    I have not personally tried any of those however.

2. As far as I know the `GDK_SCALE` environment variable only accepts integers. The `gsettings` command I mentioned above could solve this issue (provided that you use the git version of GNOME).

**Comment by kkanungo17** [comment]
Hey, really love your work :). Are you using a custom lightline colorscheme?

**Comment by elenapan** [comment]
Hey, yes I am. I forgot to upload it because my plugin manager now saves plugin related files in `~/.local/share` instead of `~/.config/nvim/`. [Here](https://pastebin.com/wMY0gY8v) is the colorscheme.

Also I am closing this because the original questions were answered. Of course you can reopen it if you have any issues.
