### ISSUE TITLE
Issue with dual Monitors

### ISSUE THREAD

**Issue by GRVYDEV** [elenapan/dotfiles#146]
Hello, I know you use single monitors however I am working on setting up a dual monitor config. Right now I have my top monitor working fine however whenever I try to open a window on my lower monitor it does not show up anywhere. The program will launch however I am left with a blank desktop wallpaper. Is there anything you can think of that would cause this? Thank you

**Comment by cortex3** [comment]
Hi @GRVYDEV, 
I do not have this problem using dual monitors. Is this still an issue can you describe how to reproduce the issue?
I'd also be interested in dual monitor support. I hope you decide to push upstream if you manage to get it working :)
From what I can tell everything is working besides that all the menu's and the lockscreen should appear on both monitors instead of just one.

**Comment by GRVYDEV** [comment]
Honestly I have no clue what I did to fix it but it works now 😆
