### ISSUE TITLE
Battery And Day Of the Week Not Working

### ISSUE THREAD

**Issue by MarkJamesXL** [elenapan/dotfiles#154]
Hello, the battery and DotW widgets are not working in the status bar, when I press the battery widget I get the image below. ![IMG_20210814_021410.jpg](https://user-images.githubusercontent.com/17765628/129426386-42af224f-0cc6-4026-b1f1-23a59c5849b1.jpg)![IMG_20210814_021438.jpg](https://user-images.githubusercontent.com/17765628/129426392-fc15773b-8e6c-41cb-8e14-a0a63c984e3c.jpg)![IMG_20210814_021355.jpg](https://user-images.githubusercontent.com/17765628/129426398-a9807ea2-1439-4933-85dd-2dfce998aec3.jpg)![IMG_20210814_022114.jpg](https://user-images.githubusercontent.com/17765628/129426570-8dc498c0-a993-46c5-b4c1-5930f465d3ed.jpg)

**Comment by MarkJamesXL** [comment]
I think the problem is with my ~/.config/omf ~/.config/fish but can't seem to understand why.

**Comment by taylor85345** [comment]
Do you have Fish set as your system shell? I recall having some issues running this theme with Fish as my default shell, since some included functions referenced /bin/sh and tried to run through scripts through Fish.

Try setting your shell back to Bash and see if that resolves the issue. If so, you'll probably want to leave your system shell as Bash or zsh, and set your terminal of choice to open Fish at launch.
