### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by tiwalayo** [elenapan/dotfiles#16]
I believe I followed all the directions for installation, but I can't seem to get the icons to load. I see them in Lovelace's theme folder, but they don't show up.  In addition, the min/max/close buttons don't load! 

[see here.](https://imgur.com/a/6ahudi7)

Neither do the exit menu's icons load.

Do you have an idea of what might cause this issue?

**Comment by elenapan** [comment]
The icons for this theme are just text. You are missing the Typicons font which includes these icons. If you install it everything should display properly.

**Comment by tiwalayo** [comment]
I changed the selected theme and bar theme at the top of rc.lua to lovelace, and a few of the icons showed up, and then I got a slew (like 13 or so) of errors to the tune of

`error in ~/.config/icon_taglist.lua:69 : attempt to index a nil value: field taglist_items_empty`

`error in ~/.config/icon_taglist.lua:75 : attempt to index a nil value: field taglist_items_focused`

`error in ~/.config/icon_taglist.lua:32 : attempt to index a nil value: field exit_screen_show`

and awesome became generally unresponsive, so I couldn't screenshot. What might've caused this?

**Comment by elenapan** [comment]
Thanks for reporting this. It was due to me not testing my older themes. I changed how xresources colors are accessed only in the new skyfall theme. Please grab the updated lovelace `theme.lua` and try again.

**Comment by tiwalayo** [comment]
Thanks! That did the trick, except for the exit screen. It has gibberish-esque symbols instead of icons. How might one fix this?

A few more questions (I can make these a new issue, if you'd like):
1. How do I disable closing tabs with middle click, as well as pasting with middle click?
2. How do I enable the sidebar's music buttons?
3. How do I make the sidebar's volume buttons increase/decrease incrementally instead of toggling between 0% and 100%?

**Comment by elenapan** [comment]
I have 2 exit screens, one with images and one with text. The text one requires the Typicons font to be installed. To use the image one, in `rc.lua` just comment out the line:
```lua
local exit_screen = require("noodle.text_exit_screen")
```
And remove the comments from:
```lua
-- local exit_screen = require("noodle.exit_screen")
```
---
Now to answer your other questions:

1. Do you mean windows instead of tabs? If so, in `titlebars.lua` check the `Mouse buttons` section. You need to delete this:
```lua
    -- Middle button - close
    awful.button({ }, 2, function ()
        window_to_kill = mouse.object_under_pointer()
        window_to_kill:kill()
    end),
```

Pasting with middle click is not an AwesomeWM setting. It is an X server setting. Not sure how to disable it, but you could look it up.

2. The sidebar music buttons work out of the box for the `mpd` music player, which I am using. If you want them to work for your own music player you need to find which terminal commands you can run to control it. Then you can just replace the mpd commands with your own.

3. The volume progressbar uses the `volume-control.sh` script from my repo to control the volume. It already works incrementally. You need to either put it somewhere in your `$PATH`, or change `sidebar.lua` so that every occurence of `volume-control.sh` is replaced with the full path to the script. If that does not fix it please open an issue about it.

**Comment by tiwalayo** [comment]
Thank you!
