### ISSUE TITLE
Awesome  - Mechanist (lovelace) - Change the settings of touchpad and Mouse 

### ISSUE THREAD

**Issue by ThinhNguyenHoang** [elenapan/dotfiles#168]
Hi, After installing correctly with the instructions in the setup page and change the rc.lua to lovelace themes. I am unable to access the settings. 

I tried to right-click the empty space on the desktop and click on the Gears Icon but nothing happen. It only lags (displace the windows) for a short moment and return to normal. No settings panel is opened. 

And another problem is i can't access my files with a File Explorer. I can't find any instruction on setting up thunar and bind it to lovelace.

I'm sorry if I bothered you. Really great Rice. The look is aesthetic but I wish it could be a bit more functional (I mean some of the Icons are not clickable).

**Comment by ThinhNguyenHoang** [comment]
> 

Sorry if I was ambiguous, the settings I desired to change was One Tap Touchpad Click, and Reverse Scrolling. 

I tried to install xfce4-settings and try to change these options but the settings are not recorded

**Comment by elenapan** [comment]
Hi there,

- The gears icon runs `awesome.restart()` on click, which is equivalent to pressing <kbd>super+shift+r</kbd>. This is why the windows lose their position. Of course, you can make this button run any command you like. Here is a patch for running the XFCE settings command instead of restarting Awesome:

   ```diff
   diff --git a/config/awesome/elemental/app_drawer.lua b/config/awesome/elemental/ap
   p_drawer.lua
   index 6be3c80..21149ad 100644
   --- a/config/awesome/elemental/app_drawer.lua
   +++ b/config/awesome/elemental/app_drawer.lua
   @@ -88,6 +88,11 @@ restart_awesome:buttons(gears.table.join(
        awful.button({ }, 1, awesome.restart)
    ))
   
   +local xfce4settings = create_button("", x.color4, x.color12)
   +xfce4settings:buttons(gears.table.join(
   +    awful.button({ }, 1, function() awful.spawn.with_shell("xfce4-settings-manage
   r") end)
   +))
   +
    -- Create the widget
    app_drawer = wibox({visible = false, ontop = true, type = "dock"})
    awful.placement.maximize(app_drawer)
   @@ -198,7 +203,7 @@ app_drawer:setup {
            create_stripe({browser, youtube, discord, telegram}, "#00000000"),
            create_stripe({mail, org, files, passwords}, x.color8.."20"),
            create_stripe({gimp, record, lutris, steam}, x.color8.."40"),
   -        create_stripe({networks, night_mode, compositor, restart_awesome}, x.colo
   r8.."60"),
   +        create_stripe({networks, night_mode, compositor, xfce4settings}, x.color8
   .."60"),
            layout = wibox.layout.flex.vertical
        },
        bg = x.background,
   :
   ```


- Window managers are not responsible for configuring the mouse. Usually these changes are made through system configuration files.

   So I will forward you to the [excellent Arch Wiki article on libinput](https://wiki.archlinux.org/title/libinput). I believe the `libinput` options you are looking for are `Option "Tapping" "on"` and `Option "NaturalScrolling" "true"`.

- As for the file manager, I have set a keybind in `keys.lua` (by default <kbd>super+F2</kbd>) which runs the `user.file_manager` command.

  You can change the file manager in:
  https://github.com/elenapan/dotfiles/blob/e952184146525f8d75ccfccb187938de1efafc54/config/awesome/rc.lua#L82

   For Thunar, set `file_manager = "thunar",`.

**Comment by ThinhNguyenHoang** [comment]
My bad,  I forgot to close the issue

I managed to configure these myself (kind of like a work-around though 😄 ) after days of digging through the wiki and threads on the forums. It's a little bit troublesome since I have no experience with lua and XFCE, but I'm glad I managed to make it work. 

Either way, I'm really thankful you showed me the more correct way to do it. Maybe I will need these in the future ❤️.  

Best regards.
