### ISSUE TITLE
Tiling/Floating Layout Not Working

### ISSUE THREAD

**Issue by williamJmelton** [elenapan/dotfiles#20]
I haven't changed the keys.lua file at all and when I press mod+s or mod+shift+s nothing is happening....just switched from i3....is this a n00b mistake or is something going wrong?

Really good work by the way, I know you've spend many hours on this

**Comment by elenapan** [comment]
If you are using the skyfall theme, there is no statusbar widget that indicates which layout you are using. The only way to find out is to notice how windows spawn.
I am not really sure why the keys are not working though. Can you spawn 3 terminals with `mod+enter` and then press `mod+s`? They should be tiled automatically.
If you want to change it so that all workspaces are on tiling layout by default (so you do not have to press `mod+s` to enable tiling all the time) you should change
```
local layouts = { l.max, l.max, l.max, l.tile , l.tile, l.max, l.max, l.max, l.tile, l.max}
``` 
so that all of them are `l.tile`.
Also, under that line you can configure the `master_width_factor` that determines the width of the first split.

**Comment by williamJmelton** [comment]
I honestly think it's just because I'm not familiar with awesome :'D
I just switched yesterday when I saw your post on unix porn. Had to have those dotfiles lol.
But thanks for your help! I think I was just doing something wrong. Sometimes my windows re-arrange themselves when I press mod+s and sometimes they dont, and I think its because of something I haven't yet learned.

**Comment by elenapan** [comment]
If you press `mod+s` while already on a tiling layout, there won't be any rearrangements. Since I am using a tiling layout on some tags and the maximized on others, maybe that is the reason it seems like `mod+s` does not always do anything.

Apart from that, if you spawn some windows as floating (e.g. `mod+shift+enter` for a floating terminal) they will not be re-arranged unless you toggle off their floating property with `mod+ctrl+space`.
Also you can check and change which clients automatically spawn as floating in the `awful.rules` section. The relevant block starts with the comment `-- Floating clients`.

I can't think of anything else that could describe your issue. Let me know if things are clear now and if you have any other issue.

**Comment by williamJmelton** [comment]
ohhhh! That was the problem I think. I thought default behavior would be to tile the floating windows....so I have to switch off the float before it will tile! Gotcha! Thanks so much for your help (and your awesome dotifles :p)
