### ISSUE TITLE
battery_daemon help

### ISSUE THREAD

**Issue by BassMatt** [elenapan/dotfiles#22]
Hi,

I've noticed in your .zshrc there's a line for `run battery_daemon`, but no notifications are appearing on my system for when I get to low battery levels.

I found [this](https://gist.github.com/AllanPamplona/d7bcdf98b874b886610fd9519085adda) script which seems to accomplish the intended purpose, but I was curious what you're using here?

**Comment by elenapan** [comment]
It was my own script that basically just checked the battery level every 30 seconds in a `while` loop, making sure to notify only one for low and critical status. However it was not very reliable so I switched to `xfce4-power-manager` until I figure out a better solution.

I will probably implement this within Awesome itself, since my battery widget already periodically checks battery level.

**Comment by BassMatt** [comment]
Does xfce4-power-manager send you notifications and such?

**Comment by elenapan** [comment]
Yeah it sends them on plug/unplug/full/low/critical.

**Comment by mustaqimM** [comment]
Here's a better way that uses dbus signals, so you get notified almost instantly:
https://github.com/lexa/awesome_upower_battery

**Comment by elenapan** [comment]
Ended up implementing it within Awesome with `acpi_listen` for instant notifications and by checking battery level every 30 seconds for low/critical/full notifications.
