### ISSUE TITLE
Icon_Taglist not working

### ISSUE THREAD

**Issue by williamJmelton** [elenapan/dotfiles#28]
I have commented out (in the bar theme skyfall.lua) the following line: 
    -- Create an icon taglist
    local icon_taglist = require("noodle.icon_taglist")

    -- Create a custom text taglist
    -- local text_taglist = require("noodle.text_taglist")

and enabled the line creating the icon taglist. When I reload awesome, however, I get no icons.

Any ideas as to why? I have poked around but am unable to find the problem. 

If this is broken, how could I go about setting up my own custom text icons using the typicon font for the text_taglist.lua?

**Comment by elenapan** [comment]
This is because the skyfall theme does not have taglist icons. You can copy the `themes/lovelace/taglist` folder into `themes/skyfall` if you want to use those icons. Otherwise you could create your own, following the naming conventions you can see in that folder.

The custom text icons and colors can be changed in `themes/skyfall/theme.lua`, look for the section starting with `-- Noodle Text Taglist`.

**Comment by williamJmelton** [comment]
I had been looking at that section of code, and as soon as I read your comment I went back to it and changed my editor font to Typicons, and I see now.

Thank you so much!

**Comment by williamJmelton** [comment]
The icon tag list btw looks and works GREAT on the skyfall bar!!! No adjustments needed
