### ISSUE TITLE
Un-commenting titlebar buttons

### ISSUE THREAD

**Issue by williamJmelton** [elenapan/dotfiles#29]
When uncommenting the titlebar buttons ( right side, in titlebar.lua ) they appear just fine, and look great with padding, however, the buttons are not clickable. When clicking it starts dragging the window instead of clicking the buttons.

**Comment by elenapan** [comment]
The line `buttons = buttons,`  refers to the mousebinds of the titlebar.
It needs to be commented **out** on the side where the clickable buttons should be, so that the mousebinds (dragging, resizing etc) do not override them.
So if you want the buttons on the right side, you should do the following:
On the right side items:
- Comment out `buttons = buttons,`
- Remove the comments from `awful.titlebar.widget.closebutton    (c),` and any other button you want to appear. You can also reorder them.

On the left side and center items:
- Remove the comments from `buttons = buttons,`

In general the rule is: If you want buttons on X side, make sure `buttons = buttons,` is on all sides except side X.

I hope it is clear for you. This is actually not an issue with my configuration, it is just AwesomeWM's way of configuring the titlebar.

**Comment by williamJmelton** [comment]
Thanks for the response! Works like a charm now. Sorry to keep opening "issues" for things that are less issue and more question lol, but sadly we don't have a question option here on GH

**Comment by elenapan** [comment]
No problem, enjoy the config.

**Comment by williamJmelton** [comment]
Is there a better way to get in touch with you? I hate to keep opening issues on your repo for my incessant questions.

**Comment by williamJmelton** [comment]
I'd like to ask you about how you style the xst terminal

**Comment by elenapan** [comment]
Actually I like it when people ask questions on Github because they are public and I can easily link to them later to answer a similar question. You could begin your issue title with "Question: ..." to differentiate it from real issues.

To answer your question about xst:
It is configured with the `~/.Xresources` file (just like urxvt, if you are familiar with that terminal).
The colors are defined exactly the same for both terminals. The st options I use are the following:
```
st.termname: st
st.borderpx: 18
st.font: monospace:size=10
st.bold_font:1
```

**Comment by williamJmelton** [comment]
Okay I was trying to use xst.variable to set things
