### ISSUE TITLE
Question about the icons

### ISSUE THREAD

**Issue by andresgabrielrc** [elenapan/dotfiles#3]
Do you manually put the icons or the system does that automatically ?  i buy the icons for my phone but i have no clue how to put them in my pc.

Thanks in advance.

**Comment by elenapan** [comment]
You have to manually extract them from your phone. If your phone is rooted and you have installed the icon pack, you can easily grab them via USB from `/Android/data/com.edzondm.linebit`. If your phone is not rooted the folder will be empty.

Someone mentioned to me that you can use [Iconzy](https://play.google.com/store/apps/details?id=com.arun.kustomiconpack) to extract the icons, regardless if your phone is rooted or not, although I have not tried it myself.

As the icon pack is for Android, you have to do everything manually.
In order to create a desktop icon pack you have to create a [specific directory structure](https://www.linux.org/threads/creating-icon-themes.11826/), handpick icons for every application, filetype, etc. and place them in the right directory.
**It will take you hours of tedious work!**

If still want to do this, `cd `/usr/share/icons`.
The directories in there are all the system's icon packs. Create a copy of any directory and rename it to "Linebit". Then replace every icon with the one you prefer.

Good luck.

**Comment by xCuri0** [comment]
@elenapan maybe make a script to rename them automatically ?

**Comment by elenapan** [comment]
While some icons have accurate names like `firefox.png` and can be automatically moved to the right directory of the icon theme, some others have the name of some obscure Android app and only a human eye / brain can recognize what icon it could correspond with. Some imagination and taste are necessary as well. It cannot be done automatically.

**Comment by xCuri0** [comment]
@elenapan but you could make one so it's exactly the same as you did it. You would just have to put your commands into a shell script

**Comment by elenapan** [comment]
I never said I made an icon theme out of them. All I did was handpick a few of them to use as my tag / widget icons. I was just answering on how to do it, in case someone with severe boredom would like to try.

**Comment by yungcheeze** [comment]
@elenapan For the lovelace theme, did you manually edit the tag/workspace icons to look different when they are focused/unoccupied etc or did they come like that from the icons pack?

**Comment by elenapan** [comment]
I manually edited them in Gimp to add dots/lines at the bottom of the icons. You can see all the tag images in `config/awesome/themes/lovelace/taglist`.
