### ISSUE TITLE
Question: music player bottom titlebar 

### ISSUE THREAD

**Issue by williamJmelton** [elenapan/dotfiles#30]
I am using the same terminal as you (xst) and starting ncmpcpp using the shortcut super+f3 (I believe not at cpu right now) and the music player spawns, but the bar in the bottom is not there. I tried adding the flag -c music to add the music class but the terminal fails to start then

**Comment by elenapan** [comment]
You are right about the shortcut. It does not set the terminal's class or name, that is why the bottom titlebar does not appear. I will fix it soon.

Inside the `super+F3` keybind this command should work:
```lua
awful.spawn(terminal .. " -c music -e ncmpcpp")
```
Make sure to leave some space after the opening quote. Without it, the command would be like this and would result in an error:
`xst-c music -e ncmpcpp`
as opposed to the correct command:
`xst -c music -e ncmpcpp`

If this still does not work, can you run `xst -c music -e ncmpcpp` from your terminal and tell me if there are any errors?

P.S: This is actually a real issue, so you can edit your title and remove "Question" from it if you like.

**Comment by williamJmelton** [comment]
That was the problem - I had omitted the space right after the quote. Also, using -c Music Terminal doesn't work - but using -c music works great and the bar is showing up!

**Comment by elenapan** [comment]
Some terminals cannot change their class but only their name, that is why I made it so the custom titlebar appears also on windows with **name** "Music Terminal". If possible, it is always better to change the class in my opinion, so that the window name is free to display the artist and title of the currently playing song.

`xst -c "Music Terminal"` will change the **c**lass, not the name, that is why the custom titlebar does not appear.
