### ISSUE TITLE
attempt to concatenate a nil value(local 'fg')

### ISSUE THREAD

**Issue by pavansrinivasmamidala** [elenapan/dotfiles#42]
It says  ~/.config/awesome/helpers.lua:28 and the above I don't understand lua and I am a beginner at coding so I couldn't solve the problem myself would you take a look at it.I cloned your repository and copied the folder into my ~/.config and there's no change but whenever I restart awesome these errors show themselves. I am using Archlinux and I am parallely running i3 and deepin if its any concern.

**Comment by elenapan** [comment]
Hi there,

You are probably missing some dependency. Also make sure you have installed `awesome-git` from the AUR instead of `awesome` from the official repositories. It is needed for the new notification appearance.

In order to debug this you could install Xephyr (in most distros the package is called `xorg-xephyr` or `xserver-xephyr`)
and run in a terminal:
```
Xephyr :1 -screen 1366x768 &
DISPLAY=:1 awesome
```
This will start awesome in a separate window. I would like you to paste the output from that terminal here when the error happens.

**Comment by pavansrinivasmamidala** [comment]
Everything works fine now but the exit screen, Logo's are not displaying is there any different font I need to install to see them. If you still need that output I can paste it. Is it easy to learn lua? I don't understand much of it but looks interesting Is it used anywhere other than in Awesome WM?

note: package name is xorg-server-xephyr in Arch Linux

**Comment by elenapan** [comment]
I do not need that input if everything works now.

The font used for the icons for the exit and lock screens is `icomoon`. I added a [download link](https://transfer.sh/yDUzi/icomoon.zip) in the fonts section of the README.

About Lua: it is a relatively easy language. If you want to start learning AwesomeWM, the hardest thing about it will not be Lua, but the amount of reading you will have to do in order to get familiar with the way of configuring things.

**Comment by pavansrinivasmamidala** [comment]
Yeah it worked thanks..!!

I am starting to learn lua will attempt to do a rice like you (but not that good obviously) in awesome and hope you will help me in some queries. 

anyway thanks for solving my problem.

I need to mention this. You are a sorceress..!!

**Comment by elenapan** [comment]
Sure, I will be happy to help. You can also post your questions in [/r/awesomewm](https://reddit.com/r/awesomewm/).

**Comment by aliza-ada** [comment]
> It says ~/.config/awesome/helpers.lua:28 and the above I don't understand lua and I am a beginner at coding so I couldn't solve the problem myself would you take a look at it.I cloned your repository and copied the folder into my ~/.config and there's no change but whenever I restart awesome these errors show themselves. I am using Archlinux and I am parallely running i3 and deepin if its any concern.

i have this problem in ubuntu and kali linux.

**Comment by elenapan** [comment]
@aliza-ada What is the output of `awesome -v`?

**Comment by aliza-ada** [comment]
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**Comment by elenapan** [comment]
As I said in [my comment above](https://github.com/elenapan/dotfiles/issues/42#issuecomment-517195467), you should make sure to install the git version of AwesomeWM. It is needed for the new notification appearance.

**Comment by aliza-ada** [comment]
u mean i install that from source? (Compile)

**Comment by elenapan** [comment]
Yes exactly.
