### ISSUE TITLE
calling a nil value in ephermal start screen 

### ISSUE THREAD

**Issue by adishourya** [elenapan/dotfiles#43]
The error is 
attempt to call a nil value(global 'start_screen_show')

If it helps ,I have installed the new awesome-wm from the aur.

**Comment by elenapan** [comment]
Ah, that is my bad. I disabled the start screen as I have no use for it anymore, but the keybinds that show it are still there.

You can re-enable the start screen by uncommenting the line:
`-- local start_screen = require("noodle.start_screen")`
in `rc.lua`.

Or you can just delete the keybinds and mousebinds that show it in `keys.lua`.
Look for the function `start_screen_show()` in order to find them.

**Comment by adishourya** [comment]
Oh. Didnt even notice the --
Thanks . Loving the rice.

**Comment by elenapan** [comment]
You are welcome :)
