### ISSUE TITLE
[Ephemeral] Sidebar search button issue

### ISSUE THREAD

**Issue by iskmar** [elenapan/dotfiles#46]
Clicking mouse 1 on search bar inside the sidebar should open rofi with -combi and mouse 3 with - run, but what it does is just spawn rofi and dissapears momentarily. Sidebar.visible = true in sidebar.lua helps remedy this issue but it's just a workaround for the problem.

**Comment by elenapan** [comment]
I have set it so that the sidebar hides when the mouse leaves. Normally, this is detected instantly, but when Rofi is running it is a special case, because Rofi does not act like a normal window. It creates (I think) an invisible overlay over all windows while running, so Awesome cannot instantly detect that the mouse has left the sidebar. That is why I have set `sidebar.visible = false` after spawning rofi. After spawning rofi I usually do not need the sidebar anymore.

If it bothers you, you can make the sidebar not hide on mouse leave by changing the `sidebar_hide_on_mouse_leave` variable in user preferences. You can just click anywhere on the desktop to hide it.

**Comment by iskmar** [comment]
I don't mind clicking, just wanted to let you know if you haven't noticed it. I still prefer KB shortcuts so it's easier with SUPER + D to call rofi.

**Comment by elenapan** [comment]
I see. I noticed it, but there is not much I can do about it. Anyway, thank you for taking the time to report it here :)
