### ISSUE TITLE
Fortune widget not working

### ISSUE THREAD

**Issue by s0344** [elenapan/dotfiles#52]
I am pretty sure fortune works on my machine, I have it installed and i tried to run `fortune -n 140 -s`and it works fine. However, the fortune widget in the start screen is empty.

**Comment by elenapan** [comment]
Hmm, I think this happens when the fortune text is too long and cannot fit in the box.
I picked 140 characters as the limit, but I guess different fonts and monitor DPI may cause the text to also have slightly different size.
 Can you try changing `140` with a smaller number in the start screen widget? Maybe `fortune -n 80 -s` will work.

**Comment by s0344** [comment]
It changed it to 40 still nothing happens.

**Comment by elenapan** [comment]
I pushed a fix. Can you test with the updated `start_screen.lua`?

**Comment by s0344** [comment]
It works! Thanks :)

**Comment by s0344** [comment]
idk if I should mention this but it is not recognizing user.terminal and user.browser etc in start_screen. I have to manually change it to "nemo "..path and "firefox "..something. Not a big trouble tho

**Comment by elenapan** [comment]
Thanks for mentioning this. There was a widget named `user` in start screen and it was overriding the global `user` settings. Fixed :)
