### ISSUE TITLE
Volume bar doesn't work with multiple sinks

### ISSUE THREAD

**Issue by longphung** [elenapan/dotfiles#61]
Hi so I plugged used my bluetooth headphones and connected it. pavuctl showed it as sink #1. The volume bar would only show the percentage of the first sink. I tried to match the second sink volume with: 
`pactl list sinks | grep Volume | awk 'FNR == 3 {print $5}'`
This works on the console but I now have no idea how to emit it as evil::volume

**Comment by elenapan** [comment]
Hi, sorry for the late response. Life has been busy lately and unlike other issues, yours actually requires some work to solve.

First of all, the command you gave me works for getting the volume level. However, in my implementation I get all the info by running the `pactl link sinks` command and then filter the info I need (volume level and mute status) with Lua. I do it in order to avoid running this command twice.

I am thinking that we need to add another evil process which detects when output devices are connected or disconnected. Every time this happens we can update a variable which will represent the active sink ID.
Then we can use this variable to filter which section of `pactl list sinks` output we need. Luckily for us the sections start with `Sink #0` or `Sink #1`.

For example, running this will only print lines after `Sink #1`.
```shell
pactl list sinks | grep -Pzo '.*Sink #1(.*\n)*'`
```

We can replace the generic `pactl list sinks` in `emit_volume_info()` with a variant of the command above in order to get info for a specific sink.

I will try to implement something whenever I have some extra time and I when get my hands on some headphones for testing purposes.

**Comment by longphung** [comment]
Ah yep, thank you very much. 

I pretty much just made a duplicate code for `emit_volume_info()` with `pactl list sinks | grep -Pzo '.*Sink #1(.*\n)*'` instead of `pactl list sinks` and put it before `pactl list sinks`. My idea was that when I connect my bluetooth headphones, the `Sink #1` which is the bluetooth device would be detected first before the other one. It has worked for me so far.

That said, I am not very sure how this really works at all and my solution is just a crude and makeshift one, since I am not very good at Awesomewm. If you have time, anything you implement for this issue would be greatly appreciated.

**Comment by elenapan** [comment]
As of 380be9d, only the active sink information is displayed at all times, and the volume level instantly updates on headphones plug/unplug.
