### ISSUE TITLE
Black border

### ISSUE THREAD

**Issue by esfomeado** [elenapan/dotfiles#66]
I have a black border all around my windows

[https://imgur.com/a/qiqtFUY](Example)

I have built awesome-wm from source.

**Comment by elenapan** [comment]
These borders are used for anti aliasing. They are completely black because you probably have not loaded any colorscheme yet. Normally they should have the color of the `background` property of the colorscheme you set in ~/.Xresources.

You can set `anti_aliasing` to `false` in `rc.lua` to completely get rid of these borders. Else, load some colorscheme you like (I suggest `lovelace` since you are using this theme) and run a compositor (like `compton`) in order to make the window corners invisible, which is needed for anti aliasing.

**Comment by esfomeado** [comment]
That solved the issue thanks.

What about this problem:
https://imgur.com/a/z4DyBXU


I have the icon pack installed as well the upower.

**Comment by elenapan** [comment]
What does `upower -e` print when you run it in terminal?

**Comment by esfomeado** [comment]
`/org/freedesktop/UPower/devices/DisplayDevice`

**Comment by elenapan** [comment]
Well, it looks like your computer does not have a battery. If that is true, you can disable the battery daemon. Open `~/.config/awesome/evil/init.lua` and remove (or comment out) the line `require("evil.battery")`.

You can also uninstall `upower` since it is not needed anymore.

**Comment by elenapan** [comment]
Closing as the original issue is resolved.
