### ISSUE TITLE
The whole theme isnt working, i just get the "vanilla" awesomewm

### ISSUE THREAD

**Issue by xhxm** [elenapan/dotfiles#67]
I'm on Ubuntu 18.04 and using AwesomeWM 4.3-4
It just says /home/user/.config/awesome/helper.lua:28: attempt to concatenate a nil value (local 'fg')
I have no clue whats wrong

**Comment by andreipavlenko** [comment]
@xhxm You should build your awesomewm from source. See #58

**Comment by Hkyx** [comment]
Hi @elenapan, @hellkitten9 

Got same problem on Manjaro, so want to try by building awesomewm myself instead of the aur repo.
If I check the official github, I saw 4.3 version only what steps did you took to build it for latest minor ? https://github.com/awesomeWM/awesome/tags
or the code is already merged into the master ? didn't saw info about that

ty, 

Hk

**Comment by elenapan** [comment]
Closing as duplicate of #58
