### ISSUE TITLE
Borders, fonts, and more

### ISSUE THREAD

**Issue by niichtsShaiaz** [elenapan/dotfiles#68]
Hi! Finally made the switch to ubuntu thanks to you.

Like in #66 I have the same borders and I tried to do what you told him to but maybe I did it wrong, perhaps another explanation could help me.

https://imgur.com/qc0BgFV

Another thing is that I'm using your zsh theme and the arrows are not working, I've installed all the nerd fonts hoping one of them would work, all placed in ``~/.local/share/fonts/``

Speaking of fonts, which font are you using in your todo app? It looks like Sofia pro ?

Also, you say you use nemo for file manager but do you have any configs for it ?

Since I assume you're on a laptop too and you use firefox, do you have 2 finger swipe to go back gesture?

Last question! Is this made for 4k res specifically, because it all seems a little bit small to me but perhaps it's just my eyes getting worse.

Currently trying to deal with remacs / emacs and I might have some more questions about that.

Sorry for all these very basic question, I'm sorry for taking up your time, I hope you don't mind

//Shiina

**Comment by elenapan** [comment]
Hi there,

**Borders**: They look fine since they have the color of the current colorscheme's background. However your terminal is not using the same colorscheme. What terminal are you using? You should configure it to use the same colors as Awesome in order for the borders to blend in with it. Alternatively, you can disable `anti_aliasing` in your `rc.lua` to get rid of the borders.

**Fonts**: After reinstalling my OS a few months ago, I also cannot get these arrows to work even with Nerd Fonts installed. They probably came from another font which I have now lost. Thus, I have replaced the old arrow character with this similar one: `❯`
The font in the todo app (Emacs) is Google Sans.

**Nemo**: It does not save its configuration files in your home directory as you would expect. You have to install `dconf-tools` in order to be able to export the config with `dconf dump /org/nemo/ > nemo_config` and import it with `dconf load /org/nemo/ < nemo_config`

[Here](https://pastebin.com/rkkDwAWB) is my exported config.

**Firefox**: I do not use swipe gestures in general. I use the Vimium addon to navigate with the keyboard. Some of Firefox's native keybinds are also useful, like the `Alt+Left arrow` for going back, `Ctrl+L` to focus the url bar, `Ctrl+d` to add page to favorites etc.

**4K**: No the theme is not specifically made for 4K res, it is made to scale with DPI. Fonts look clearer in high DPI, even in small sizes. That could be the reason why they may look unreadable to you (because of low DPI). I suggest increasing the taskbar font size a bit.

Let me know if you have more questions.

**Comment by niichtsShaiaz** [comment]
I think I fixed the borders and fonts now, the arrows are working again yay.
Is the nemo config supposed to change the colours of it or is it supposed to be white?

To increase the font size for the taskbar I would have to edit ``~/.config/awesome/bars/Theme-I'm-Using`` and then on line 13 ``font = "icomoon #`` Correct ?

**Title bar** I'm trying to increase the size of the icons, I think changing `` local gen_button_size = dpi(12)`` is changing the first 2, but not the close button / Heart, is there another place for that or is it not possible to change it?

After looking into a bit further I believe the  Ephemeral theme has the wrong fallback colours in the config.

I saw in your reddit post that you would share the emacs config once you'd cleaned it up a bit, is that something you've done now or is it still in the works?

Thank you so much again for helping a newbie ^_^

**Comment by elenapan** [comment]
**Taskbar Font**: Not all themes include a taskbar. The `ephemeral` bar takes the font from your theme's `tasklist_font` variable as you can see:
https://github.com/elenapan/dotfiles/blob/a146b497e98cbc0e20178b9212b4d5f48db0ef12/config/awesome/bars/ephemeral.lua#L239

Thus you need to go to `~/.config/awesome/themes/<Theme you are using>/theme.lua` and change `theme.tasklist_font` to your liking.

**Titlebar heart button**: This button is generated a bit differently than the others. I use the heart symbol from Material Icons font for it. You have to change the font size in `gen_text_button` function.
https://github.com/elenapan/dotfiles/blob/997650801a7f6a60b1c1753f40e5f610669a1b2c/config/awesome/titlebars.lua#L89-L93

**Ephemeral fallback colors**: You are right about this but the truth is I only set up fallback colors so Awesome does not crash when you do not have any colorscheme loaded. Most people use their own colorschemes anyways.

**Emacs config**: I have been using Emacs more and more lately, mostly for the convenience of using a single text editor instead of 2. Previously I would take notes in Emacs and code in Vim. By now, I have ported most of my Vim configuration to Emacs. However I am having performance issues I am trying to solve right now. Vim just seems faster at everything and I am debating if I should keep using Emacs or not. In any case, whenever I am happy with the state of my config I will post it in a separate repo.

**Comment by niichtsShaiaz** [comment]
I'll be patiently waiting for the emacs repo, thank you so much for your time and effort explaining it to me!! ❤️
