### ISSUE TITLE
Is there like a tutorial on how to make all of these stuff?

### ISSUE THREAD

**Issue by Joe23232** [elenapan/dotfiles#70]
I want to fork your work and make some of the stuff work on KDE such as the lock screen, is this possible?

If so then is there like some tutorial as to how to code and make custom stuff such as lock screens?

**Comment by elenapan** [comment]
Hi there,

All the widgets you can see in my screenshots were created with the AwesomeWM framework. In order to make them work on other window managers or desktop environments, you will have to find a way to spawn AwesomeWM with all window management disabled.
This is not yet possible, but there is a discussion here:
https://github.com/awesomeWM/awesome/issues/2635

For now you could try to develop widgets for KDE.
Here are a few tutorials:
https://techbase.kde.org/Development/Tutorials/Plasma5
https://zren.github.io/kde/docs/widget/
https://techbase.kde.org/Development/Tutorials/Plasma5/QML2/GettingStarted

Check out [the KDE store for available widgets](https://store.kde.org/browse/cat/418/ord/rating/) you can get inspiration from. You can download and extract the `.plasmoid` files which are basically `.zip`s and study their sources.

Good luck!

**Comment by Joe23232** [comment]
@elenapan Hi, I am new to GNU/Linux so I apologise for my lack of understanding.

The AwesomeWM framework that you have mentioned, this is only controls how the windows behave, it doesn't control the taskbar, the lockscreen etc, am I correct?

How was your lockscreen created? Was it through the AwesomeWM?

**Comment by elenapan** [comment]
AwesomeWM controls the windows AND allows you to create widgets such as a taskbar, lockscreen or anything else you imagine.

Its name is misleading, it is not just a window manager. This is why I called it a framework.

The lockscreen was created with AwesomeWM and at least until https://github.com/awesomeWM/awesome/issues/2635 is implemented, it only works when the `awesome` window manager is running.

**Comment by Joe23232** [comment]
I see that makes sense. Which window manager is the best to use out there? I just want to know since I want to rice my GNU/Linux setup?

If I were to edit your lockscreen, is it easy to edit using some config file or do I have to use the Lua programming language?

**Comment by elenapan** [comment]
Well, my opinion is biased, but for me the best window manager is AwesomeWM, However, I am always reluctant to recommend it to a beginner because it requires some time and effort to learn. KDE can be customized a lot, so if you are satisfied with it, I suggest you stick with it.
If you want to go for something minimal but still familiar and super customizable, you can start with Openbox.
If you want to give proper tiling a shot, you could start with i3 or bspwm.
In these cases, you can complement your desktop with Conky widgets, which can work on any window manager. [Here is a collection of Conkies you could take inspiration from.](https://github.com/addy-dclxvi/conky-theme-collections)
Lastly, If you care about having complete control of how your whole desktop behaves (not just windows) and being able to make beautiful widgets from scratch, then by all means go for AwesomeWM. It can do a lot more than that of course, but in my opinion, this is its biggest strength.



About editing the lockscreen: Yes, you will have to use Lua to configure it, since it was written in Lua, but do not be discouraged, it is an easy language.

**Comment by Joe23232** [comment]
@elenapan 

> About editing the lockscreen: Yes, you will have to use Lua to configure it, since it was written in Lua, but do not be discouraged, it is an easy language.

Well if it is easy for me to use the language I could try and install KDE at first and then configure AwesomeWM.

But couple of last questions, can AwesomeWM be configured as a tilling window manager as well and which one is more customisable, editing KDE's themes or AwesomeWM themes?

**Comment by elenapan** [comment]
AwesomeWM is definitely more customizable than KDE.

KDE is "meant" to be customized through a GUI and not by manually editing configuration files, although it is possible to do both.


Editing small details of a theme is straightforward in both AwesomeWM and KDE

AwesomeWM example snippet (Lua):
```lua
theme.border_width  = dpi(0)
theme.border_normal = "#000000"
theme.border_focus  = "#ffffff"
theme.border_radius = dpi(6)
```

KDE example snippet (configuration file):
```
BorderBottom=1
BorderLeft=1
BorderRight=1
ButtonHeight=16
```

For more advanced theme customization it is easier to configure AwesomeWM in my opinion, since it gives you the ability to do almost anything. In order to do that for KDE you will have to edit KWin's source code and recompile.

**Comment by Joe23232** [comment]
That seems not too hard, thanks for the example I think I am going to stick with AwesomeWM :)

One question mate.
![image](https://user-images.githubusercontent.com/34926497/73617575-479f6300-4674-11ea-890e-217c3f3143c5.png)


Were you the original creator of this? Cause this was posted on Redit and a link was provided to this repo.

Do you know what icon pack you are using in this image?

**Comment by elenapan** [comment]
Yes I am the creator. I am using [Linebit for Android](https://play.google.com/store/apps/details?id=com.edzondm.linebit&hl=en).

**Comment by Joe23232** [comment]
It looks very nice the way you created it :)

Sorry mate I keep asking more questions but I am trying to add someone's preconfigured awesomeWM setup and later on I will use your configurations and combine it with the other person's work.

This is the other person's repo https://github.com/worron/awesome-config

So I did do `git clone https://github.com/worron/awesome-config.git` and I then moved the directory into `~/.config/awesome`.

How do I get awesome to run this guy's configuration?

**Comment by elenapan** [comment]
He has instructions [here](https://github.com/worron/awesome-config#installation-and-usage). Once you do them, logout and in the login screen there should be a button that lets you select an Awesome session instead of KDE session.

**Comment by Joe23232** [comment]
@elenapan That is what I was reading but I don't get this.

I have all the required files in this directory `/home/test/.config/awesome/`

> Then edit rc.lua to select wanted config.

```
-----------------------------------------------------------------------------------------------------------------------
--                                                   Base setup                                                      --
-----------------------------------------------------------------------------------------------------------------------

-- Configuration file selection
-----------------------------------------------------------------------------------------------------------------------
--local rc = "colorless.rc-colorless"

--local rc = "color.red.rc-red"
--local rc = "color.blue.rc-blue"
--local rc = "color.orange.rc-orange"
--local rc = "color.green.rc-green"

local rc = "shade.ruby.rc-ruby"
--local rc = "shade.steel.rc-steel"

require(rc)
```

This is what is inside my `rc-lua` inside `/home/test/.config/awesome/`. What and where am I supposed to modify?

**Comment by elenapan** [comment]
You can pick whichever one of these themes you want to enable. Right now `shade.ruby` is enabled. If you want to change the theme to something else, just comment out (put `--` in front) the `shade.ruby` line and remove the comment from the theme you want to switch to. Then restart Awesome.

**Comment by Joe23232** [comment]
@elenapan 

![image](https://user-images.githubusercontent.com/34926497/73676495-94347e00-4708-11ea-9633-d750eb479914.png)

Not too sure what is going on this is the error I get after restarting AwesomeWM.

**Comment by Joe23232** [comment]
There was something wrong with the folder so I redownloaded it and it works

**Comment by elenapan** [comment]
Ok great. Closing the issue since the original question was answered.

**Comment by Joe23232** [comment]
Thanks mate, honestly your work looks great. I am going actually build my own rice from awesomeWM in its vanilla form and I am going to take inspiration of your work in terms of UI while I use the other guy's work for functionality wise.

Can I just have a copy of your config file for vim please? I love the colour layout.

**Comment by elenapan** [comment]
My vim config is already uploaded here under [config/nvim](https://github.com/elenapan/dotfiles/tree/master/config/nvim).

**Comment by Joe23232** [comment]
@elenapan Sorry last couple of questions in regards to vim.

1. Is it possible for me to enable mouse functionality such as clicking, highlighting text etc (just like with a normal text editor like notepad)?
2. Is it possible to have support for autosuggest for languages such as Rust?

**Comment by elenapan** [comment]
1. Yes, you need `set mouse=a` in your config to enable mouse support. It is already enabled on mine.
2. Yes, but I have never used Rust inside or outside Vim so I cannot help you with that. You can google something like "Vim Rust setup" for more info.

**Comment by Joe23232** [comment]
Thanks mate, I hope to see more of your future work, where can I follow you on?

**Comment by elenapan** [comment]
For now I only post on Reddit. Not sure if there is a follow button there. Apart from that you can just check this repo for new themes.

**Comment by Joe23232** [comment]
Oh ok thanks mate :)

You might want to try out `alacritty` terminal, it is much faster than other terminals such as `exterm` and it is very customisable. DistroTube did a video on this.

**Comment by Joe23232** [comment]
@elenapan hey man sorry to bother you again, I just have a few questions. You know the way how you customised your rice for awesomeWM? Is it possible for a user to make OpenBox function similarly to how your rice functions on awesomeWM?

How much openbox is easier compared to awesoemWM, have you used other tilling window managers?

**Comment by elenapan** [comment]
Openbox is one of the easiest and at the same time most customizable window managers. I was using it for a long time and I highly recommend it.
You do not need to be a coder to customize Openbox.

You can find a ton of themes in the following links:
https://www.box-look.org/browse/cat/140/ord/latest/
https://github.com/fikriomar16/OBTheme-Collections
https://github.com/addy-dclxvi/openbox-theme-collections

Tint2 is a very customizable statusbar commonly used with Openbox. It can even be customized with a GUI (`tint2conf`).
Some themes here:
https://github.com/addy-dclxvi/tint2-theme-collections

Most tiling window managers are limited when it comes to appearance customization, that is why I would suggest you use Openbox. If you need tiling, you can use Openbox with a tiling script, like [pytyle](https://github.com/BurntSushi/pytyle1).
If you want a real tiling window manager, the most customizable one when it comes to window appearance, apart from Awesome, is in my opinion [herbstluftwm](https://github.com/herbstluftwm/herbstluftwm/).

> Is it possible for a user to make OpenBox function similarly to how your rice functions on awesomeWM?

I am not sure what you mean with "function similarly". If you mean window tiling behavior, then yes, because `pytyle` uses the same master-slave tiling algorithm. If you mean window appearance, then almost. Openbox is pretty customizable in that regard, but it still cannot do, for example, titlebars on the left or right of the window.
If you mean widgets like custom lock screen etc, then yes, if you do not mind using some independent tools which work on any window manager. For example:
- Lock screen: https://github.com/reorr/mantablockscreen
- Exit screen: `oblogout` with [this theme](https://www.deviantart.com/bruhensant/art/Theme-Oblogout-Adeos-667513097)
- App drawer: `rofi -show drun -fullscreen` with icons enabled
