### ISSUE TITLE
Vim colorsheme when true color is enabled

### ISSUE THREAD

**Issue by paradoxsurpeme** [elenapan/dotfiles#76]
When `set termguicolors` option is enabled in vim the colorscheme breaks. It seems that it only works for 16 bit color. Is there any way to use it when TRUE COLOR is enabled in vim ?

**Comment by elenapan** [comment]
I think I would have to hardcode the color hexcodes in the colorscheme for that to work, for example like [solarized.vim](https://github.com/altercation/vim-colors-solarized/blob/master/colors/solarized.vim) does.
So it would not adapt to your terminal's colorscheme anymore, but you would have to change the colors manually every time you use a different terminal colorscheme.

**Comment by MatthiasGrandl** [comment]
is there really no other way? also stumbled across this, because I would really love to use https://github.com/norcalli/nvim-colorizer.lua but not enough to not have my terminal colors...

**Comment by elenapan** [comment]
Well, one way I can think of is to make a script that generates a custom colorscheme file. But the script will have to be executed whenever you change your colorscheme. 

In order for the colors to be updated while vim is still running, after generating the colorscheme, the colorscheme should be reloaded in vim with `:colorscheme lena-true-color`.

The script below grabs the colors from Xresources. If your terminal does not use Xresources, you can simply parse your terminal's config in a similar way in order to grab the colors.

```shell
#!/usr/bin/env bash
colorscheme="$HOME/.config/nvim/colors/lena-true-color.vim"

# Get xresources colors
xrdb="$(xrdb -query)"
xbg="$(echo "$xrdb" | grep -m 1 background: | awk '{print $2}')"
x0="$(echo "$xrdb" | grep -m 1 color0: | awk '{print $2}')"
x1="$(echo "$xrdb" | grep -m 1 color1: | awk '{print $2}')"
# ... and so on, until color15

# Generate the true color colorscheme using xresources colors
cat > "$colorscheme" <<EOF
hi ColorColumn         guibg=$x0
hi SpellBad            guifg=$x1     guibg=$xbg  gui=underline
" ... and so on, for all highlight groups
EOF
```
