### ISSUE TITLE
Volume-control not working?

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#82]
Hi, any reason for the volume.control.sh not be working?

I have all it takes to be installed. All other notificationss work (screenshot, telegram, etc.), just the volume dont

How do i test this on terminal, i type on the terminal and it gives this back

![2020 05 11-19 05 10 screenshot](https://user-images.githubusercontent.com/17055027/81616696-7c3d5c00-93d3-11ea-8fda-78519a2eddae.png)
(Option -R unknown, in english)

Which argument should i use? I tried volume-control.sh -up and stuff and it don't. 

Any help will be appreciated.

**Comment by elenapan** [comment]
That is because in `volume-control.sh` I am using [notify-send.sh](https://github.com/vlevit/notify-send.sh) instead of the original `notify-send`. It has some extra options like `-R` which allows replacing a notification text instead of creating a new one (useful for spammy notifications like volume, brightness etc).

However, volume control is now built into the AwesomeWM config, so you do not need to use `volume-control.sh` anymore. Your volume keys should work out of the box, as well as the volume slider in the sidebar. Notifications should work out of the box as well.

**Comment by hrqmonteiro** [comment]
Well, my volume keys run out of the box, but the notifications for volume change is still not working. Any tips?

I even removed the volume-control.sh from my bin, now my vol keys adjust volume but i still got no notifications..

**Comment by hrqmonteiro** [comment]
Even with notify-send.sh and volume-control.sh or without, i simply can't get ANY notifications for volume, and i don't know why, is becoming frustrating lol

I'm new to awesome, i was using openbox, and even my script i used on openbox for controlling volume and sending notifications is not working here..

**Comment by elenapan** [comment]
Yeah the notifications work for me. Keep in mind I have made it so that notifications are not sent if the sidebar is visible or Pavucontrol (volume manager) is focused.
https://github.com/elenapan/dotfiles/blob/06458c76a299a5e1dad85241a0c5a5891f5ee9ae/config/awesome/notifications/volume.lua#L10-L17

If that is not the problem, let's test if the volume daemon actually works.

Can you try running this in your terminal? It will make AwesomeWM send a notification every time your volume changes (until the next restart of AwesomeWM).
```shell
awesome-client '
local naughty = require("naughty")
awesome.connect_signal("evil::volume", function()
    naughty.notification({ title = "volume changed" })
end)
'
```

Adjust your volume and let me know if a notification pops up.

**Comment by hrqmonteiro** [comment]
Yes, i know that it doesnt work with pavu or bar.

But i ran this on the terminal, it shows no notification whatsoever..

**Comment by elenapan** [comment]
Ok. Can you run `pactl subscribe` in a terminal and then try changing your volume?

It should print a bunch of events every time you change your volume, like so:
```
Event 'new' on client #5333
Event 'change' on client #5333
Event 'change' on sink #1
...
```

Let me know if it prints anything or not.

**Comment by hrqmonteiro** [comment]
![2020 05 13-10 49 11 screenshot](https://user-images.githubusercontent.com/17055027/81820762-89b42c80-9520-11ea-8983-417388dd05b0.png)

Legend: Evento = event
Alterar = change
Novo = new
Remover = remove

**Comment by elenapan** [comment]
Ok thank you, I figured it out. So the volume daemon is looking for the word `sink` in order to trigger an update (and notification), but since your output is in a different language, it cannot find `sink` and thinks there is no update.
https://github.com/elenapan/dotfiles/blob/06458c76a299a5e1dad85241a0c5a5891f5ee9ae/config/awesome/evil/volume.lua#L50-L53

You can replace `sink` with `destino` in the snippet above, but I am afraid it is not the only place that needs changes.
You might also have issues with the microphone daemon that looks for `source`, and other daemons whose output differs depending on system language.

I will try to find language agnostic way to fix this.

Related:
https://github.com/elenapan/dotfiles/issues/44#issuecomment-527229170

**Comment by elenapan** [comment]
Do any of these 2 commands print events in English?

```shell
LC_ALL=C sh -c 'pactl subscribe'
```

```shell
LANG=en_US.UTF-8 sh -c 'pactl subscribe'
```

**Comment by hrqmonteiro** [comment]
Well, i don't think the language is a problem, actually, because:

In my laptop with Void, the language is english, and no notifications
Also, i changed "sink" to "destino", and no change happened

And right now, i changed my language to english (and reversed the change in sink), and no notifications still. I think the problem is another, don't you think?

![2020 05 13-11 36 41 screenshot](https://user-images.githubusercontent.com/17055027/81826315-30033080-9527-11ea-8479-747416ded20a.png)

**Comment by hrqmonteiro** [comment]
> Do any of these 2 commands print events in English?
> 
> ```shell
> LC_ALL=C sh -c 'pactl subscribe'
> ```
> 
> ```shell
> LANG=en_US.UTF-8 sh -c 'pactl subscribe'
> ```

![2020 05 13-11 37 29 screenshot](https://user-images.githubusercontent.com/17055027/81826443-4e692c00-9527-11ea-8bc8-2ede0666b3ba.png)
![2020 05 13-11 37 39 screenshot](https://user-images.githubusercontent.com/17055027/81826444-4f01c280-9527-11ea-8a9b-ae8f5f8b6cda.png)

**Comment by elenapan** [comment]
> And right now, i changed my language to english (and reversed the change in sink), and no notifications still. I think the problem is another, don't you think?

Hmm, in that case can you try if this whole command prints anything at all when changing volume?
```shell
LC_ALL=C sh -c 'pactl subscribe 2> /dev/null | grep --line-buffered "sink"'
```

Also could you post the output of these 2 commands?
```shell
LC_ALL=C sh -c 'pactl list sinks | grep "%"'
```

```shell
LC_ALL=C sh -c 'pactl list sinks | grep Mute'
```

**Comment by hrqmonteiro** [comment]
> > And right now, i changed my language to english (and reversed the change in sink), and no notifications still. I think the problem is another, don't you think?
> 
> Hmm, in that case can you try if this whole command prints anything at all when changing volume?
> 
> ```shell
> LC_ALL=C sh -c 'pactl subscribe 2> /dev/null | grep --line-buffered "sink"'
> ```
> 
> Also could you post the output of these 2 commands?
> 
> ```shell
> LC_ALL=C sh -c 'pactl list sinks | grep "%"'
> ```
> 
> ```shell
> LC_ALL=C sh -c 'pactl list sinks | grep Mute'
> ```

The first one: (First print when i hitted vol 1 time, and then when i kept hitting)

![2020 05 13-11 55 57 screenshot](https://user-images.githubusercontent.com/17055027/81828959-eb2cc900-9529-11ea-8832-f8961bdcccd1.png)
![2020 05 13-11 56 02 screenshot](https://user-images.githubusercontent.com/17055027/81828961-ebc55f80-9529-11ea-994b-d1330b6d6b17.png)

The second and third one:

![2020 05 13-11 56 22 screenshot](https://user-images.githubusercontent.com/17055027/81828988-f253d700-9529-11ea-8bda-25e6625eadb6.png)

**Comment by hrqmonteiro** [comment]
Update, for some reason now it is showing on the laptop built-in sound device

![2020 05 13-14 20 28 screenshot](https://user-images.githubusercontent.com/17055027/81844068-102b3700-953e-11ea-9e8f-ef31df9b1c99.png)

But if i switch to my hdmi sound it disappears

**Comment by elenapan** [comment]
I see. Then it is related to this https://github.com/elenapan/dotfiles/issues/61.

I will push a fix for this in the next few days, but for now you can make these changes:
```diff
diff --git a/config/awesome/evil/volume.lua b/config/awesome/evil/volume.lua
index 6f0a98e..a8ac236 100644
--- a/config/awesome/evil/volume.lua
+++ b/config/awesome/evil/volume.lua
@@ -10,9 +10,9 @@ local volume_old = -1
 local muted_old = -1
 local function emit_volume_info()
     -- Get volume info
-    awful.spawn.easy_async("pactl list sinks", function(stdout)
+    awful.spawn.easy_async_with_shell("pacmd list-sinks | awk '/\\* index: /{nr[NR+7];nr[NR+11]}; NR in nr'", function(stdout)
         local volume = stdout:match('(%d+)%% /')
-        local muted = stdout:match('Mute:(%s+)[yes]')
+        local muted = stdout:match('muted:(%s+)[yes]')
         local muted_int = muted and 1 or 0
         local volume_int = tonumber(volume)
         -- Only send signal if there was a change
```

**Comment by hrqmonteiro** [comment]
Thanks! Is working all fine. I appreciate very much, and thanks for the patience with a newbie haha, glad you could help me
