### ISSUE TITLE
Have you used both XMonad and Awesome

### ISSUE THREAD

**Issue by Joe23232** [elenapan/dotfiles#84]
Hey man I am curious to know if you have used `xmonad` before. If so like, then were you like experienced in it?

If so like what makes you chose `awesome` over `xmonad`? I am sorry for opening up an issue over here, but I am looking for the right tilling window manager to use.

Thank you :)

**Comment by elenapan** [comment]
I have not used Xmonad.

Both of them are configured by writing code which is always a good sign for customizability. AwesomeWM is literally **made** to be customized to the last detail. I am not sure if the philosophy of Xmonad is the same and how much of its internals are exposed to the user.

I would say that AwesomeWM is easier to customize, mostly because Lua is a much easier language than Haskell and also because AwesomeWM is more popular than Xmonad, which means that you will not have trouble getting help from other users.

The only active Xmonad user I know of that has a decent configuration is [karetsu](https://github.com/karetsu/xmonad-aloysius/). I suggest you ask them the same question.
