### ISSUE TITLE
White borders on radius corner of the windows when using compton/picom

### ISSUE THREAD

**Issue by hrqmonteiro** [elenapan/dotfiles#86]
Is this happening just here, the borders on the windows are turning like a white square when using compton/picom shadows:

![2020 06 07-22 50 33 screenshot](https://user-images.githubusercontent.com/17055027/83985939-68711100-a911-11ea-9c03-783077360f32.png)

**Comment by hrqmonteiro** [comment]
![2020 06 07-22 53 13 screenshot](https://user-images.githubusercontent.com/17055027/83986014-b423ba80-a911-11ea-911f-bd29b495c6e8.png)

This one on a black background is easier to see

**Comment by elenapan** [comment]
The `ephemeral` decoration theme rounds clients with the method described [here](https://github.com/elenapan/dotfiles/wiki/Anti-aliasing) in order to achieve anti-aliased corners. It requires a compositor to be running, but it does not look nice with all types of shadows.

You can change your picom shadow configuration to make the shadows rounder and softer:
```
shadow-radius = 15;
shadow-offset-x = -10;
shadow-offset-y = -10;
shadow-opacity = 0.4;
```

Or change the decoration theme to something other than `ephemeral` in `rc.lua`:
https://github.com/elenapan/dotfiles/blob/091fca68047fa3d7e9952464d6832af6d0ff5b39/config/awesome/rc.lua#L23-L29

**Comment by elenapan** [comment]
This should not happen on windows with the last update. It should only happen on wiboxes that use the method described [here](https://github.com/elenapan/dotfiles/wiki/Anti-aliasing) for anti-aliased shaping.

It is easy to override. Simply apply the anti-aliased shape defined at the bottom the wibox's `setup` block directly on the wibox itself.

Closing as the original issue is now fixed.
