### ISSUE TITLE
How did you learn how to configure awesome?

### ISSUE THREAD

**Issue by Joe23232** [elenapan/dotfiles#87]
Hey man, I am curious to know how did you learn how to configure awesome? I am trying to learn how to configure awesome but I am finding it to be a huge struggle in terms of how to configure stuff. May I know what you did personally to learn how to configure awesome?

**Comment by ceuk** [comment]
Are you the same guy that's made 4 posts in the last 24hrs to the sub? 😅 

Just learn Lua first and then read the [Awesome docs](https://awesomewm.org/). Also using rices like this one is a great way to see how things are done and learn about the various key concepts.

**Comment by Joe23232** [comment]
> Are you the same guy that's made 4 posts in the last 24hrs to the sub? 😅

Are you referring to the awesomeWM sub? Lol yeah I am unix(some random digits) guy xD.

> Just learn Lua first and then read the Awesome docs. Also using rices like this one is a great way to see how things are done and learn about the various key concepts.

Thanks mate I will do that. It was a huge struggle I could barely change anything (only a few things I managed to change). I have tried reading some other dude's config and he litreally has moved everything around to the point where I could not understand anything. And with @elenapan I am not too sure where is his `rc.lua` file.

**Comment by ceuk** [comment]
Her rc.lua is in the [root Awesome folder](https://github.com/elenapan/dotfiles/tree/master/config/awesome)

Even if it seems more complex I'd recommend starting from someone else's work and tweaking rather than trying to work your way up from scratch. I did exactly the same but you realised in the end that 90% of the little issues, how to structure things etc have been done far better by some others already. This repo, for example, has some pretty useful [utility functions](https://github.com/elenapan/dotfiles/blob/master/config/awesome/helpers.lua) that abstract some of the quirks/more verbose parts of awesome amongst other things.

If you're not going to use it as your daily driver that's different I guess, and I see the appeal of a clean slate too. Either way, you'll get there :) the Awesome API isn't that big conceptually once you get your head around it. The main things are off the top of my head are:

* Key bindings
* Client rules
* Theme and decorations
* Tag list
* Task list
* Notifications
* Widgets

**Comment by elenapan** [comment]
- My first tip is to complete these tutorials in this order (if you haven't already):
    1. [My first Awesome](https://awesomewm.org/apidoc/documentation/07-my-first-awesome.md.html)
    2. [Default configuration file documentation](https://awesomewm.org/apidoc/documentation/05-awesomerc.md.html#)
    3. [Change Awesome appearance](https://awesomewm.org/apidoc/documentation/06-appearance.md.html)

- My second tip is to always keep the AwesomeWM documentation open whenever you are editing your config.

    When I started the documentation was a bit lacking. Sometimes I would have to dive into the source code to understand how things worked. Nowadays there are a lot more examples you can study in order to figure out how stuff works. Whenever you see an example in the documentation, put it in your config, try it out and customize it to your liking.

- My final tip is to always have a goal in mind.

    I suggest you draw (in your mind, on paper, anywhere) how your desktop wants to look like. Divide that into pieces. Start with the most simple things first:
    + Wallpaper
    + Window borders, titlebars and buttons
    + Notification settings
    + Taglist/tasklist settings
        Check the premade non-default examples in the configuration, they will help you a lot:
        + https://awesomewm.org/apidoc/widgets/awful.widget.taglist.html
        + https://awesomewm.org/apidoc/widgets/awful.widget.tasklist.html

    Then you can move on to harder stuff, like creating your own widgets from scratch.

    You can always study the code of other AwesomeWM users. Just keep in mind that most of us who have a huge AwesomeWM config prefer to separate it into multiple files.

    If you are interested in my config, check out [this section in my README](https://github.com/elenapan/dotfiles#awesomewm-configuration-file-structure) that explains what each file and directory is useful for.

Good luck.

**Comment by Joe23232** [comment]
@ceuk @elenapan Thank you guys for your help I will check out the suggested resources :)
