### ISSUE TITLE
Round Borders

### ISSUE THREAD

**Issue by RequiemsGhost** [elenapan/dotfiles#89]
I'm not sure what I did wrong but it seems that I can't round my borders. Is there anyway I could fix this?
https://user-images.githubusercontent.com/64157573/87232937-ff0d7380-c390-11ea-8235-f7487a46d32d.png

**Comment by elenapan** [comment]
Hi there,

I am using [this picom fork](https://github.com/ibhagwan/picom) in order to round the window corners. If you do not want to use it, but you prefer AwesomeWM to round the windows itself, you can enable rounding by removing the comments from the `decorations.enable_rounding()` line here:

https://github.com/elenapan/dotfiles/blob/d5b72a03389fddd80a2734a81da3b9e0ce1a24fe/config/awesome/decorations/themes/ephemeral.lua#L9-L12

**Comment by elenapan** [comment]
I have now added a [wiki entry](https://github.com/elenapan/dotfiles/wiki/Rounded-corners) for this question.
