### ISSUE TITLE
Firefox theme for lovelace

### ISSUE THREAD

**Issue by stricte** [elenapan/dotfiles#9]
Hi,

i have noticed that Firefox theme uses manta colors, what produces unreadable context menu on lovelace. 

PS great job. Lovelace was main reason i have switched to awesomeWM.

**Comment by elenapan** [comment]
Yeah, I did not update the Firefox theme since I was not using Firefox on that /r/unixporn screenshot.

I just uploaded `lovelace.css` which works with dark GTK themes. Context menus should work fine now.

Let me know if everything is ok.

**Comment by stricte** [comment]
Looks good.

One more thing if I can: tabs and main window doesn't have buttons. Tabs for close and main window for close, minimize and maximize. Is there sth I missed?

**Comment by elenapan** [comment]
The tab close button is disabled in `tabs.css`. I don't really need it since I use `middle click` or `Ctrl+W` to close tabs.
If you want the close button, just comment out or delete this section:
```
/* no close button */
.tabbrowser-tab .tab-close-button {
    display: none !important;
}
````

The buttons for the main window (close, maximize, minimize) are supposed to be next to the tabs on the right if you have `browser.tabs.drawInTitlebar` set to `true` in `about:config`. However when set it to true, I only get empty space where the buttons are supposed to be. Not sure how to fix this one. Some DE's like KDE, Gnome, Budgie etc somehow make it work. I will need to investigate how they do it at some point.

**Comment by stricte** [comment]
Thank you. Once again, great job.
