### ISSUE TITLE
Battery Error notifications

### ISSUE THREAD

**Issue by SNELON** [elenapan/dotfiles#90]
Hi, I am running on a desktop pc so i dont need battery notifications. Is there an easy way to disable this? (I am a complete noob at modding linux this is my first attempt at ricing)

**Comment by elenapan** [comment]
Yep, you can just delete the `require("evil.battery")` in your `~/.config/awesome/evil/init.lua`.

**Comment by SNELON** [comment]
> Yep, you can just delete the `require("evil.battery")` in your `~/.config/awesome/evil/init.lua`.

Okay thank you! I am also having an issue with a lot of the icons not launching anything. Like for example the settings icon just sends a notification error.

**Comment by elenapan** [comment]
That could be because the buttons are trying to launch apps that are not installed on your system.
Take a look at `~/.config/awesome/apps.lua` as well as the user preferences section in `rc.lua`, and adjust the apps used to the ones you like.

If you still have issues, let me know what the notification errors say so I can help you.

**Comment by elenapan** [comment]
Closing since the original issue has been solved. If you still have issues with the app launchers, please open a new issue.
