### ISSUE TITLE
Doom Emacs colorscheme

### ISSUE THREAD

**Issue by longphung** [elenapan/dotfiles#96]
Just as the title, I really like org mode and how uniform you keep your Doom Emacs config with the overall theme. I just recently installed Doom Emacs just for the org mode I have no idea how to change them with the xfiles colorscheme you have.

**Comment by elenapan** [comment]
For Doom emacs, I have created a `doom-lena` theme which, instead of hardcoding colors, it grabs them from Xresources.

I just uploaded it [here](https://github.com/elenapan/dotfiles/tree/master/config/doom/themes).

One thing to note is that I have set my `$DOOMDIR` to `~/.config/doom` but if I remember correctly, the default is `~/.doom.d`. So place the theme accordingly.

Finally, add this to your `config.el` to load the theme on startup:
```lisp
(setq doom-theme 'doom-lena)
```

Let me know if you need more help.

**Comment by Tanish2002** [comment]
I tried your doom theme but it doesn't seem to work for me, do I need to get some specific package for it to work?

**Comment by elenapan** [comment]
Closing since the solution was provided.
