### ISSUE TITLE
Screen tearing with Picom

### ISSUE THREAD

**Issue by ProgrammAbel** [elenapan/dotfiles#99]
Hi, I seem to be getting a bit of screen tearing while scrolling in websites, and while watching YouTube videos. I have a suspicion that it has something to do with your Picom config because my old config didn't have this problem. Does anyone else have this problem?

**Comment by elenapan** [comment]
Hi, I just updated my picom config, let me know if the issue is still there.

https://github.com/elenapan/dotfiles/blob/master/config/picom/picom.conf

**Comment by ProgrammAbel** [comment]
Thanks for getting back. I had already copied the contents into `picom.conf` instead of `compton.conf`, so the commit doesn't change much for me. I still experience the issue, unfortunately.

**Comment by elenapan** [comment]
I did add some new settings that could affect tearing in the updated version.

If you have tried it and the issue is still there, you could just grab your old config and only add the `blur-exclude` and `shadow-exclude` parts from mine.

I use the shadow rules to remove shadows from the dock and sidebar, and the blur rules to only blur the transparent part of the lock screen. The rest of the settings in my config are optional.

**Comment by ProgrammAbel** [comment]
Okay, thanks! After a bit of experimenting, the [patch file I created](https://gist.github.com/ProgrammAbel/6066e30b124b32bc7711791c3dea4c77) should be able to patch the default `picom.conf` (from `/etc/xdg/picom.conf`) to allow this.
